### ISSUE TITLE
template support for WA-compliant complex images

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/cwd_base#26]
_"Partner issue" with https://github.com/CU-CommunityApps/CD-demo/issues/49_

### Two new templates
* media/media--image.html.twig
* media/field--media--field-aria-description.html.twig

### Example usage on CD Demo multidev
* Basic page with a complex image embedded in the body, and a "non-complex image" embedded in the body:
https://cplx-img-cd-demo.pantheonsite.io/test-basic-page-complex-image-and-other-images
* Individual media pages, which show original/non-image-style images -- one complex, one non-complex:
https://cplx-img-cd-demo.pantheonsite.io/media/11
https://cplx-img-cd-demo.pantheonsite.io/media/3

_(See associated PR.)_

### To do
* [x] Stick these templates on a site that doesn't have field_aria_description and make sure nothing breaks (so it's safe to push out this code with an update to cwd_base).
* [x] Handle "what about when there's no image style," like when you view a media entity page and it uses "None (original image)" in the display settings? (ack!)
* [x] Test with an image attached to an image/entity reference field.
  * Examples with an image via media/entity reference field:
https://cplx-img-cd-demo.pantheonsite.io/news-and-events/news
https://cplx-img-cd-demo.pantheonsite.io/news-and-events/news/yaks-campus
* [x] Finish partner issue on CD Demo repo -- well, almost-finish, because when this issue is done, there'll be a new cwd_base release, which we'll need to grab on CD Demo, and then we can close the partner-cd-demo issue... (but other than the "cwd_base release" situation, this issue is dependent on the cd demo issue)

**Comment by alisonjo315** [comment]
Example implementation on Biotech (no guarantees this link lasts):
https://dev-biotech.pantheonsite.io/example-basic-page-technical-image

**Comment by alisonjo315** [comment]
Input from Hank on Slack last night:

> The aria-label will override the alt text (which will be ignored by screen readers), so the automated accessibility tools will probably complain about that (as well as about the article/heading issue). You’d have to ensure  that the content people are aware that the aria-label must contain the alt text plus the added clause. Using article.sr-only (instead of div) with the h2 seems a pretty cool solution, much better than longdesc. Is there a URL where we could test this with screen readers?

Alison's reply on Slack:

> There's no URL for testing the alternate implementation Tone proposed.

**Comment by ama39** [comment]
I don't think people doing content entry would need to worry about entering a special manner of aria-label. It would be automatically created, drawing in the alt text and appending the extra hint. The content entry experience would only involve populating two simple fields:

1. A concise alt attribute
2. A long description

Everything else would be generated using these two parts.

**Comment by alisonjo315** [comment]
Sounds cool to me, I'll ping the WA channel again for any further feedback -- I'm especially interested in feedback on:
> The aria label will override the alt text... so the automated accessibility tools will probably complain about that (as well as about the article/heading issue).

**Comment by alisonjo315** [comment]
> Stick these templates on a site that doesn't have field_aria_description and make sure nothing breaks (so it's safe to push out this code with an update to cwd_base).
Done:
https://updates-vpue-main.pantheonsite.io/about-us
https://updates-vpue-main.pantheonsite.io/
https://updates-vpue-main.pantheonsite.io/highlights/another-demo-test-highlight-example

**Comment by alisonjo315** [comment]
I've decided to merge as-is.  I'm not comfortable changing to the implementation without input from the WA team about what I mentioned in my [June 29 comment](https://github.com/CU-CommunityApps/cwd_base/issues/26#issuecomment-651275065).

I would fully support and pitch in on a follow-up implementation change if someone else initiates, but I don't feel comfortable with doing it myself :)

(Or maybe if the DUX meeting could give it a full discussion and come to a consensus and share back? -- or not, if no one cares -- and I don't mean that sarcastically!)
