### ISSUE TITLE
search in html.html.twig

### ISSUE THREAD

**Issue by alisonjo315** [CU-CommunityApps/cwd_base#7]
Make the search section of html.html.twig an overridable block.

See also:
* on cwd_project: [Split head/foot sections of html.html.twig into head/foot templates](https://github.com/CU-CommunityApps/cwd_project/issues/13)
* #46

**Comment by woodseowl** [comment]
+1

**Comment by woodseowl** [comment]
I think that a pass through html.html.twig + page.html.twig to extract the typical components (search, cu-header, site-footer) so they can be individually overridden makes good sense, too. I did this a bit on ovpia-migrations and find myself doing it again on SCL. That may be a good project to look to as a jump start for some top-level templating tweaks.

**Comment by alisonjo315** [comment]
Makes you wonder whether this should be in cwd_base or cwd_project -- AND/OR, does it matter?!

**Comment by alisonjo315** [comment]
Closing because outdated.

See #46 and https://github.com/CU-CommunityApps/cwd_project/issues/22
